### ISSUE TITLE
Use old mobile display (resources)

### ISSUE THREAD

**Issue by ghost** [nalajcie/orienteering_clock#1]
Here some usefull resources for using old mobile displays with Arduino:
* http://andybrown.me.uk/downloads/
  * https://github.com/andysworkshop/xmemtft

**Comment by nalajcie** [comment]
We don't want to use old mobile displays for this kind of clock (they are waaay too small).

Currently we're using quite large 7-segment led display (single digit is 90x120mm).

I'll try to post more detailed instructions regarding build in the future, for now the finished clock looks like that:
![Finished clock](https://lh3.googleusercontent.com/g35UWGhVJ7BzO53yQgYFB6HoZm_7o8n5eygPtaV_eBKS9U-ocaQG423FNROoFGLdkqKQBA1XE3QZiXM=w1920-h936-rw)
